"""Move status to settlement

Revision ID: 8fa97ca0a2f5
Revises: 02b4622b23f8
Create Date: 2026-07-21 06:49:17.606467

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8fa97ca0a2f5'
down_revision = '02b4622b23f8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.drop_column('status')

    with op.batch_alter_table('settlement', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('settlement', schema=None) as batch_op:
        batch_op.drop_column('status')

    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.VARCHAR(length=20), nullable=False))

    # ### end Alembic commands ###
